#!/usr/bin/env bash
tmp_dir="$HOME/Pictures/Test"
tmp_cover_path=$tmp_dir/cover.png

artlink="$(playerctl metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"

if [ $(playerctl metadata mpris:artUrl) ]; then
	curl -s $artlink --output $tmp_cover_path
else
	cp ~/.config/eww/images/music.png $tmp_cover_path
fi
