#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.bin/eww"

eww daemon

## Open widgets
run_eww() {
  ${EWW} open-many \
    background \
    profile \
    system \
    clock \
    uptime \
    music \
    github \
    reddit \
    twitter \
    youtube \
    weather \
    apps \
    mail \
    logout \
    sleep \
    reboot \
    poweroff \
    folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
  touch "$FILE"
  run_eww
else
  ${EWW} close-all
  rm "$FILE"
fi
