"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character] # The name of the module we are configuring is 'character'
success_symbol = "[ ❯](bold green)"
error_symbol = "[ ❯](bold red)"
vimcmd_symbol = "[ ❯](bold green)"
vimcmd_visual_symbol = "[ ❯](bold yellow)"
vimcmd_replace_symbol = "[ ❯](bold purple)"
vimcmd_replace_one_symbol = "[ ❯](bold purple)"

[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
style = "bold blue"


[package]
symbol = " "
style = 'bold yellow'

[nodejs]
symbol = "󰋘 "

[python]
symbol = " "

[lua]
symbol = " "
style = "yellow"

[git_branch]
symbol = " "
format = "on [$symbol$branch(:$remote_branch)]($style) "


[cmake]
symbol = "󰲉 "

[golang]
symbol = " "

[rust]
symbol = " "

[c]
symbol = " "

[docker_context]
format = 'with [  ](cyan bold)'

[bun]
symbol = " "
style = "white"

[dotnet]
format = "via [$symbol($version)]($style) "
symbol = "🐳 "
style = "bold cyan"
version_format = "v${major}"

[ruby]
symbol = ' '
disabled = true

[java]
symbol = " "
format = 'use [${symbol}(${version} )]($style)'

[gradle]
symbol = " "

[kotlin]
symbol = " "
