#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &
~/.config/dunst/load.sh &
~/.config/polybar/launch.sh float &
nitrogen --restore &
picom &
ibus_daemon &
imwheel &

# bspc monitor -d  爵    ﴬ   漣
bspc monitor -d גּ הּ          
#bspc monitor -d 1 2 3 4 5 6 7 8 9 
# bspc config automatic_scheme spiral
#bspc config initial_polarity first_child
bspc config border_width 0
bspc config window_gap 10 
bspc config focused_border_color "#4c566a"
bspc config normal_border_color "#4c566a"
bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_by_distance true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Specific settings per app

# bspc rule -a notion-app-enhanced desktop='^6' follow=off
bspc rule -a discord desktop='^8' follow=on
#bspc rule -a TelegramDesktop desktop='^8' follow=on
#bspc rule -a Caprine desktop='^8' follow=on
#bspc rule -a pomotroid state=floating rectangle=600+503+145

bspc rule -a Spotify desktop='^7' follow=on
# bspc rule -a qBittorrent desktop='^9' follow=on

bspc rule -a Font-manager state=floating follow=on center=true
#bspc rule -a Gnome-calculator state=floating follow=on center=true rectangle=400x400+0+0
