#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &
~/.config/dunst/load.sh &
~/.config/polybar/launch.sh float &
nitrogen --restore &
picom &
ibus_daemon &
eww daemon &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 0
bspc config window_gap 9
bspc config focused_border_color "#a3be8c"
bspc config normal_border_color "#4c566a"
bspc config presel_feedback_color "#2e3448"

bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_by_distance true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Specific settings per app
bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

bspc rule -a discord desktop='^6' follow=on

bspc rule -a solaar desktop='^1' follow=on state=floating center=true
bspc rule -add code desktop=2 follow=on
bspc rule --add org.pwmt.zathura desktop=2

bspc rule -a qBittorrent desktop='^9' follow=on

bspc rule -a Font-manager state=floating follow=on center=true
#bspc rule -a Gnome-calculator state=floating follow=on center=true rectangle=400x400+0+0
