#!/usr/bin/sh

# require fzf to menu select and imageMagick to convert

# get path of picture
cd ~/Pictures/
dir="$(find -type f | fzf --prompt="הּ " --layout=reverse --height=50% --info=inline --border --margin=1 --padding=1 | sed 's/^..//g' | tr -d '\n')"

# get size of picture
width="$(identify "$dir" | awk '{print $3}' | rev | awk -F'x' '{print $NF}' | rev)"
height="$(identify "$dir" | awk '{print $3}' | awk -F'x' '{print $NF}')"

# convert use imageMagick
convert -size "$width"x"$height" xc:none -draw "roundrectangle 0,0,"$width","$height",10,10" png:- | convert "$dir" -matte - -compose DstIn -composite round.png
convert round.png \( +clone -background black -shadow 100x30+0+0 \) +swap -bordercolor none -border 15 -background none -layers merge +repage final.png

# final image is in Folder Pictures and name as final.png
rm -rf round.png
sxiv final.png
