#!/bin/bash

STATUS="$(mpc status)"
COVER="/tmp/music_cover.png"
MUSIC_DIR="$HOME/Music"

ffmpeg -i "${MUSIC_DIR}/$(mpc current -f %file%)" "${COVER}" -y &>/dev/null
cp /tmp/music_cover.png ~/Music/
STATUS=$?
