#!/bin/bash

STATUS="$(mpc status)"
COVER="/tmp/.music_cover.png"
MUSIC_DIR="$HOME/Music"

ffmpeg -i "${MUSIC_DIR}/$(mpc current -f %file%)" "${COVER}" -y &>/dev/null
STATUS=$?

if [ "$STATUS" -eq 0 ]; then
	echo "$COVER"
else
	echo "images/music.png"
fi
