#!/usr/bin/sh
dir="$(find -type f | fzf --prompt="הּ " --layout=reverse --height=50% --info=inline --border --margin=1 --padding=1 | sed 's/^..//g' | tr -d '\n')"

last_dir="$(echo "$dir" | awk -F/ '{print $NF}')"
lastdir="'$last_dir'"
pastdir="$(echo "$dir" | rev | cut -d/ -f2- | rev)"
fulldir="$pastdir/$lastdir"
echo "$fulldir" | xclip -selection c
